NiTs update
ana-cc/ack-frequency pull request #1
Opened 2022-11-16 11:34 UTC by gorryfair

2022-11-16 14:27 UTC, ana-cc commented on draft-ietf-quic-ack-frequency.md
>  Ack-Eliciting Threshold and Request Max Ack Delay values to be no more than a
maybe 'no more' should be 'no larger'?

2022-11-16 14:27 UTC, ana-cc commented on draft-ietf-quic-ack-frequency.md
>  values to be no more than a congestion window and an estimated RTT,
maybe 'no more' should be 'no larger'?

... this feels a bit repetitive

2022-11-16 14:27 UTC, ana-cc commented on draft-ietf-quic-ack-frequency.md
> +QUIC ACK_FREQUENCY frames are protected by the normal quic security mechanisms {{QUIC-TRANSPORT}}).
s/quic/QUIC

2022-11-16 14:27 UTC, ana-cc commented on draft-ietf-quic-ack-frequency.md
> +
hmm, the first sentence can be rewritten as:

Improperly configured  or malicious senders could cause standards-compliant receivers to acknowledge more frequently than their available resources permit, thus causing a Denial Of Service (DOS) attack.  

I'm not sure about the second sentence, what was the gist of it? Senders have control of many aspects of the receiver behaviour anyway and so this is not an issue for well-configured servers?

2022-11-16 19:34 UTC, gorryfair commented
Seems like the new text updates in this PR will resolve these problems.

2022-11-21 10:44 UTC, ana-cc requested changes

2022-11-21 10:44 UTC, ana-cc commented on draft-ietf-quic-ack-frequency.md
> +congestion controllers (e.g. {{I-D.ietf-tsvwg-aqm-dualq-coupled}} that mark more frequently than classic ECN {{?RFC3168}}.
(e.g. {{I-D.ietf-tsvwg-aqm-dualq-coupled}} needs a ')' at the end

2022-11-21 10:44 UTC, ana-cc commented on draft-ietf-quic-ack-frequency.md
> +values to be respectively smaller than a congestion window and nolonger than
s/nolonger/no longer/

2022-11-21 10:44 UTC, ana-cc commented on draft-ietf-quic-ack-frequency.md
> +AN Improperly configured or malicious sender could cause standards-compliant receivers to
s/AN Improperly/An improperly/

2022-11-21 10:44 UTC, ana-cc commented on draft-ietf-quic-ack-frequency.md
> +Denial Of Service (DOS) attack. However, A sender has control of many aspects of
s/A/a/

2022-11-21 10:44 UTC, ana-cc commented on draft-ietf-quic-ack-frequency.md
> +the receiver behaviour and therefore there is no additional threat from a well-configured sender.
s/there is no additional threat from a well-configured sender/for a well-configured sender this causes no additional threat/

2022-11-21 15:37 UTC, merged